<?php
// $Id$

/**
 * @file   GMS Misc module.
 */

/**
 * Implements hook_menu().
 */
function gms_misc_menu() {

  $items = array();
  
  /*
    $items['gms_misc_map/%'] = array(
	'title' => t('GMS Map Coordinates'),
    'page callback' => 'gms_misc_map_location',
	'page arguments' => array(1),
    'access arguments' => array('access content'), 
	'type' => MENU_CALLBACK,
  );
  */
  
    $items['gms_misc_map'] = array(
	'title' => t('GMS Map Coordinates'),
    'page callback' => 'gms_misc_map_location',
    'access arguments' => array('access content'), 
	'type' => MENU_CALLBACK,
  );
  
	// render any drupal page via ajax
	$items['get/ajax'] = array(
    'page callback' => 'gms_misc_ajax_get_ajax', // Render HTML
    //'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'gms_misc_ajax_callback',  // Magic goes here
  );  
	
  return $items;
}


function gms_misc_map_location() {
	
  global $mydata;	
	
  $data = $_POST;
  
	//$data['myVar'] = 'hello';
	//$data['formState'] = $form_state;

  //$form_state['values']['title'] = $data['name'];
  
  
  drupal_json_output($data);
  exit();

}


function gms_misc_node_presave($node) {
  if ($node->type == "project") {
	// when saving a project node
	//if (isset($node->body['und'])) {	// uncomment this line for php imports or disable gms_misc module
		// json decode the value of the node body
		// (previously set by map.js)
		$json = $node->field_location_temp['und'][0]['value'];
		//echo "gms_misc.module | json: ".$json."<br/>";
		  
		$data = json_decode($json);
		 
		$ctr = 0;

		echo "gms_misc.module | data:".print_r($data,1)."<br/>";
		// set the values of the json string to discrete values in field_project_locations
		$node->field_project_locations['und'] = null;	// comment out this line for php imports
		foreach ($data as $val) {  
			$lat = $val->geometry->coordinates[1];
			$lng = $val->geometry->coordinates[0];
			$node->field_project_locations['und'][$ctr]['lat'] = $lat;
			$node->field_project_locations['und'][$ctr]['lng'] = $lng;
			$node->field_project_locations['und'][$ctr]['lat_sin'] = sin(deg2rad($lat));
			$node->field_project_locations['und'][$ctr]['lat_cos'] = cos(deg2rad($lat));
			$node->field_project_locations['und'][$ctr]['lng_rad'] = deg2rad($lng);  
			$ctr++;
		}

		//dpm($node);
	//}	// uncomment this line for php imports  
  }
}


function gms_misc_user_login(&$edit, $account)
{
  // Your logic will set $redirection to the desired location
  $redirection = 'maps/projects';
  
// Unless there is already a redirection going, or the user is trying to reset his password, we redirect to $redirection.
  if (empty($_GET['destination'])
    && !is_null($redirection)
    && (!isset($_POST['form_id']) || $_POST['form_id'] != 'user_pass_reset'))
  {
    $_GET['destination'] = $redirection; // Should we use $edit['redirect'] instead..?
  }
}

function gms_misc_ajax_get_ajax() {
	// The function will receive the array of arguments after the "get/ajax" prefix
  $path = implode('/', func_get_args());
  $render_string = menu_execute_active_handler($path, FALSE);
  return $render_string;
}

function gms_misc_ajax_callback($page_callback_result) {
	// Only render content and validates return
  $content = is_string($page_callback_result) ? $page_callback_result : drupal_render($page_callback_result);
  print $content;
}


function gms_misc_js_alter(&$javascript, &$vars) {
	// Swap out jQuery to use an updated version of the library.
	//$javascript['misc/jquery.js']['data'] = drupal_get_path('module', 'jquery_update') . '/jquery.js';
  $path = current_path();
  //drupal_set_message(t($path),'status');
  if ($vars['type'] == 'project' || $path == 'maps/projects') {
    $ip_geoloc_path = drupal_get_path('module','ip_geoloc').'/js/ip_geoloc_gmap_multi_loc.js';
    $gms_ip_geoloc_path = drupal_get_path('module', 'gms_misc') . '/gms_ipgeoloc.js';
    $javascript[$ip_geoloc_path] = $gms_ip_geoloc_path;
    drupal_add_js($gms_ip_geoloc_path);
  }
	
}